services:
  racket-server:
    image: racket-server
    build:
      context: ./racket-server
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: react-frontend
    build:
      context: ./frontend
    ports:
      - "8080:80" 
    depends_on:
      - racket-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
