services:
  racket-server:
    image: racket-server
    build:
      context: ./racket-server
    networks:
      - app-network

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - racket-server
    environment:
      - VITE_API_URL=http://racket-server:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
